a = 10
b = "string"
Ten = input("Tên của bạn")
Ho_dem = input("Họ và tên đệm của bạn:")
Tuoi = input("Tuổi của bạn là bao nhiêu")

print("Tên đầy đủ của bạn là:", Ho_dem, Ten)
print("Tuổi hiện tại là:", Tuoi)

# Nguoi phong van thu cung tra loi
'''
gt = input("Gioi tinh: ")
st = input("So thich: ")
du = input("mon an ma thu cung bi di ung:")
print("Giới tính thú cưng của bạn là:", gt)
print("Giới tính thú cưng của bạn là:", gt)
'''
i = float(input("a = "))



